# Generated by Django 6.0.2 on 2026-02-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'Общие вопросы'), ('delivery', 'Доставка')], default='general', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ элемент',
                'verbose_name_plural': 'FAQ элементы',
                'ordering': ['id'],
            },
        ),
    ]
