# Generated by Django 6.0.2 on 2026-05-12 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Чёрный Чиж', max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(default='Профессиональный питомник с многолетним опытом разведения породистых собак', verbose_name='Подзаголовок')),
                ('mission_title', models.CharField(default='Наша миссия', max_length=255, verbose_name='Заголовок миссии')),
                ('mission_text', models.TextField(default='', verbose_name='Текст миссии')),
                ('cta_title', models.CharField(default='Присоединяйтесь к нам', max_length=255, verbose_name='Заголовок CTA')),
                ('cta_text', models.TextField(default='Следите за новостями питомника и новыми помётами в наших социальных сетях', verbose_name='Текст CTA')),
            ],
            options={
                'verbose_name': 'Страница «О нас»',
                'verbose_name_plural': 'Страница «О нас»',
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(default='Свяжитесь с нами удобным для вас способом — мы всегда на связи', verbose_name='Подзаголовок')),
                ('address', models.CharField(default='Москва, Россия', max_length=255, verbose_name='Адрес')),
                ('address_note', models.CharField(default='Посещение питомника — по предварительной записи', max_length=255, verbose_name='Примечание к адресу')),
                ('banner_title', models.CharField(default='Остались вопросы?', max_length=255, verbose_name='Заголовок баннера')),
                ('banner_text', models.TextField(default='Напишите нам, и мы ответим в ближайшее время. Мы открыты для общения и всегда рады помочь с выбором питомца.', verbose_name='Текст баннера')),
                ('banner_email', models.EmailField(default='info@sharpei.club', max_length=254, verbose_name='Email баннера')),
            ],
            options={
                'verbose_name': 'Страница «Контакты»',
                'verbose_name_plural': 'Страница «Контакты»',
            },
        ),
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='Год')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='consumer.aboutpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Веха',
                'verbose_name_plural': 'Вехи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='consumer.aboutpage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Принцип',
                'verbose_name_plural': 'Принципы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Электронная почта')], max_length=32, verbose_name='Тип')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('href', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='consumer.contactspage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100, verbose_name='Дни')),
                ('hours', models.CharField(max_length=100, verbose_name='Часы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='consumer.contactspage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='vk, messenger, instagram, whatsapp', max_length=50, verbose_name='Ключ иконки')),
                ('label', models.CharField(max_length=100, verbose_name='Отображаемое название')),
                ('value', models.CharField(max_length=255, verbose_name='Отображаемое значение')),
                ('href', models.URLField(max_length=500, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='consumer.contactspage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
                'ordering': ['order'],
            },
        ),
    ]
