#!/bin/bash
set -e

ESCAPED_PASSWORD="$(echo "$DB_PASSWORD" | sed "s/'/''/g")"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    -- Пользователь только для приложения: без SUPERUSER, может создавать объекты в своей БД
    CREATE USER ${DB_USER} WITH PASSWORD '${ESCAPED_PASSWORD}' NOSUPERUSER NOCREATEROLE CREATEDB LOGIN;
    CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$DB_NAME" <<-EOSQL
    GRANT ALL ON SCHEMA public TO ${DB_USER};
    GRANT CREATE ON SCHEMA public TO ${DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${DB_USER};
EOSQL
