FROM node:24-alpine

WORKDIR /frontend-app

RUN npm install -g --force yarn

COPY frontend/package.json ./package.json

RUN yarn install

COPY frontend/ .

ARG APP_NAME=user-app

ENV APP_NAME=${APP_NAME}

RUN yarn workspace ${APP_NAME} build
