export { AdvantagesSection } from './AdvantagesSection'
export { BreedAboutSection } from './BreedAboutSection'
export { FAQSection } from './FAQSection'
export { FormSection } from './FormSection'
export { HeroSection } from './HeroSection'
export { KnowledgeBaseSection } from './KnowledgeBaseSection'
export { PuppiesSection } from './PuppiesSection'
