# Generated by Django 6.0.2 on 2026-02-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
