# Generated by Django 6.0.2 on 2026-02-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_avatar_color_user_avatar_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_color',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_initials',
        ),
    ]
