# Generated by Django 6.0.2 on 2026-02-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('unpublished', 'Не опубликован')], default='unpublished', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('unpublished', 'Не опубликован')], default='unpublished', max_length=32),
        ),
        migrations.DeleteModel(
            name='InfoStatus',
        ),
    ]
