# Generated by Django 6.0.2 on 2026-02-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('education', '0003_alter_course_status_alter_article_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='breed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='common.breed'),
        ),
    ]
