# Generated by Django 6.0.2 on 2026-04-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_article_author_article_author_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='HTML-контент статьи (санитизируется при сохранении).'),
        ),
    ]
