# Generated by Django 6.0.2 on 2026-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_usertaskattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
