# Generated by Django 6.0.2 on 2026-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_coursetask_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_lesson_article',
            field=models.BooleanField(default=False, help_text='True если статья создана автоматически для урока курса.'),
        ),
    ]
