# Generated by Django 6.0.2 on 2026-02-24 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='breeds/')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='BreedDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.TextField()),
                ('character_rating', models.IntegerField()),
                ('character_text', models.TextField()),
                ('adaptability_rating', models.IntegerField()),
                ('adaptability_text', models.TextField()),
                ('care_rating', models.IntegerField()),
                ('care_text', models.TextField()),
                ('activity_rating', models.IntegerField()),
                ('activity_text', models.TextField()),
                ('breed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='common.breed')),
            ],
            options={
                'verbose_name': 'Описание породы',
                'verbose_name_plural': 'Описания пород',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('on_sale', 'В продаже'), ('booked', 'Забронирован'), ('sold', 'Куплен')], max_length=32)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=16)),
                ('color', models.CharField(max_length=255)),
                ('potential', models.CharField(choices=[('pet', 'Домашний питомец'), ('show', 'Шоу'), ('breeding', 'Разведение')], max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_group', models.CharField(choices=[('puppy', 'Щенок'), ('adult', 'Собака')], default='adult', max_length=16)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='common.breed')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
        migrations.CreateModel(
            name='DogDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='dogs/documents/')),
                ('name', models.CharField(max_length=255)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='common.dog')),
            ],
            options={
                'verbose_name': 'Документ собаки',
                'verbose_name_plural': 'Документы собак',
            },
        ),
        migrations.CreateModel(
            name='DogParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец')], max_length=16)),
                ('breed', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.breed', verbose_name='Порода')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='common.dog')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.dog')),
            ],
            options={
                'verbose_name': 'Родитель собаки',
                'verbose_name_plural': 'Родители собак',
            },
        ),
        migrations.CreateModel(
            name='DogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='dogs/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='common.dog')),
            ],
            options={
                'verbose_name': 'Фото собаки',
                'verbose_name_plural': 'Фото собак',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('messenger', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='common.dog')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
