# Generated by Django 6.0.2 on 2026-02-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BreedDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.TextField()),
                ('character_rating', models.IntegerField()),
                ('character_text', models.TextField()),
                ('adaptability_rating', models.IntegerField()),
                ('adaptability_text', models.TextField()),
                ('care_rating', models.IntegerField()),
                ('care_text', models.TextField()),
                ('activity_rating', models.IntegerField()),
                ('activity_text', models.TextField()),
                ('breed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='common.breed')),
            ],
        ),
    ]
