# Generated by Django 6.0.2 on 2026-02-09 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='breeds/')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='PuppyPotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Потенциал щенка',
                'verbose_name_plural': 'Потенциалы щенков',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PuppySex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Пол щенка',
                'verbose_name_plural': 'Пол щенков',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PuppyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Статус щенка',
                'verbose_name_plural': 'Статусы щенков',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BreedDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.TextField()),
                ('character_rating', models.IntegerField()),
                ('character_text', models.TextField()),
                ('adaptability_rating', models.IntegerField()),
                ('adaptability_text', models.TextField()),
                ('care_rating', models.IntegerField()),
                ('care_text', models.TextField()),
                ('activity_rating', models.IntegerField()),
                ('activity_text', models.TextField()),
                ('breed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='common.breed')),
            ],
            options={
                'verbose_name': 'Описание породы',
                'verbose_name_plural': 'Описания пород',
            },
        ),
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('color', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppies', to='common.breed')),
                ('potential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puppies', to='common.puppypotential')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puppies', to='common.puppysex')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puppies', to='common.puppystatus')),
            ],
            options={
                'verbose_name': 'Щенок',
                'verbose_name_plural': 'Щенки',
            },
        ),
        migrations.CreateModel(
            name='PuppyParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_as_father', to='common.puppy')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_as_mother', to='common.puppy')),
                ('puppy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='common.puppy')),
            ],
            options={
                'verbose_name': 'Родители щенка',
                'verbose_name_plural': 'Родители щенков',
            },
        ),
        migrations.CreateModel(
            name='PuppyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='puppies/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='common.puppy')),
            ],
            options={
                'verbose_name': 'Фото щенка',
                'verbose_name_plural': 'Фото щенков',
                'ordering': ['order', 'id'],
            },
        ),
    ]
