# Generated by Django 6.0.2 on 2026-02-23 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='common.article'),
        ),
        migrations.AddField(
            model_name='coursestep',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='common.course'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='common.coursestep'),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='common.courselesson'),
        ),
        migrations.AddField(
            model_name='coursetaskquestion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='common.coursetask'),
        ),
        migrations.AddField(
            model_name='coursetaskanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='common.coursetaskquestion'),
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='common.breed'),
        ),
        migrations.AddField(
            model_name='dog',
            name='potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.animalpotential'),
        ),
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.animalsex'),
        ),
        migrations.AddField(
            model_name='dog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.animalstatus'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='common.infostatus'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='common.infostatus'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='common.infotag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='common.infotag'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='common.breed'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='potential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.animalpotential'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.animalsex'),
        ),
        migrations.AddField(
            model_name='puppy',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.animalstatus'),
        ),
        migrations.AddField(
            model_name='puppydocument',
            name='puppy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='common.puppy'),
        ),
        migrations.AddField(
            model_name='puppyparents',
            name='breed',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.breed', verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='puppyparents',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.dog'),
        ),
        migrations.AddField(
            model_name='puppyparents',
            name='puppy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='common.puppy'),
        ),
        migrations.AddField(
            model_name='puppyphoto',
            name='puppy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='common.puppy'),
        ),
        migrations.AddField(
            model_name='request',
            name='puppy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='common.puppy'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddConstraint(
            model_name='dog',
            constraint=models.UniqueConstraint(fields=('id', 'breed'), name='dog_id_breed_unique'),
        ),
        migrations.AddConstraint(
            model_name='puppy',
            constraint=models.UniqueConstraint(fields=('id', 'breed'), name='puppy_id_breed_unique'),
        ),
        migrations.AddConstraint(
            model_name='puppyparents',
            constraint=models.UniqueConstraint(fields=('dog',), name='unique_dog_as_parent'),
        ),
        migrations.AddConstraint(
            model_name='puppyparents',
            constraint=models.UniqueConstraint(fields=('puppy', 'role'), name='unique_role_per_puppy'),
        ),
    ]
