# Generated by Django 6.0.2 on 2026-02-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('international_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('for_sale', 'В продаже'), ('reserved', 'Забронирован'), ('sold', 'Куплен')], max_length=255)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('potential', models.CharField(choices=[('pet', 'Домашний питомец'), ('breed', 'Разведение'), ('show', 'Шоу')], max_length=255)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.breed')),
            ],
        ),
        migrations.CreateModel(
            name='PuppyParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_as_father', to='common.puppy')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_as_mother', to='common.puppy')),
                ('puppy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='common.puppy')),
            ],
        ),
    ]
