# Generated by Django 6.0.2 on 2026-02-24 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dog',
            constraint=models.UniqueConstraint(fields=('id', 'breed'), name='dog_id_breed_unique'),
        ),
        migrations.AddConstraint(
            model_name='dogparent',
            constraint=models.UniqueConstraint(fields=('parent',), name='unique_dog_as_parent'),
        ),
        migrations.AddConstraint(
            model_name='dogparent',
            constraint=models.UniqueConstraint(fields=('child', 'role'), name='unique_role_per_child'),
        ),
    ]
