# Generated by Django 6.0.2 on 2026-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_puppy_puppyparents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='international_name',
        ),
        migrations.AddField(
            model_name='puppy',
            name='description',
            field=models.TextField(blank=True, help_text='Описание щенка', null=True),
        ),
    ]
