# Generated by Django 6.0.2 on 2026-02-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_fill_status_sex_potential'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuppyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='puppies/documents/')),
                ('name', models.CharField(max_length=255)),
                ('puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='common.puppy')),
            ],
            options={
                'verbose_name': 'Документ щенка',
                'verbose_name_plural': 'Документы щенков',
            },
        ),
    ]
