# Generated by Django 6.0.2 on 2026-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
