# Generated by Django 6.0.2 on 2026-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogphoto',
            options={'ordering': ['-is_main', 'order', 'id'], 'verbose_name': 'Фото собаки', 'verbose_name_plural': 'Фото собак'},
        ),
        migrations.AddField(
            model_name='dog',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dogdocument',
            name='document_type',
            field=models.CharField(choices=[('puppy_card', 'Щенячья карточка'), ('vet_passport', 'Ветеринарный паспорт')], default='puppy_card', max_length=32),
        ),
        migrations.AddField(
            model_name='dogphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
