# Generated by Django 6.0.2 on 2026-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_puppydocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppydocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='puppies/documents/'),
        ),
    ]
