# Generated by Django 6.0.2 on 2026-04-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_dog_published_photo_main_doc_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='apartment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='common.breed'),
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='house',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='prepayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='prepayment_status',
            field=models.CharField(blank=True, choices=[('not_paid', 'Не внесена'), ('paid', 'Внесена')], default='not_paid', max_length=32),
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('consultation', 'Консультация'), ('booking', 'Бронирование'), ('waiting_list', 'Лист ожидания')], default='consultation', max_length=32),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='request',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
