# Generated by Django 6.0.2 on 2026-02-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_request_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
