# Generated by Django 6.0.2 on 2026-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_puppy_international_name_puppy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
