# Generated by Django 6.0.2 on 2026-02-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_puppy_use_status_sex_potential_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='puppy',
            options={'verbose_name': 'Щенок', 'verbose_name_plural': 'Щенки'},
        ),
        migrations.AddField(
            model_name='puppy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='puppies/'),
        ),
    ]
