# Generated by Django 6.0.2 on 2026-02-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_puppyphoto_migrate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='photo',
            field=models.ImageField(null=True, upload_to='breeds/'),
        ),
    ]
