/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as PuppiesRouteImport } from './app/routes/puppies'
import { Route as LibraryRouteImport } from './app/routes/library'
import { Route as ContactsRouteImport } from './app/routes/contacts'
import { Route as AboutRouteImport } from './app/routes/about'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as PuppiesBreedIdRouteImport } from './app/routes/puppies.$breedId'
import { Route as PuppiesBreedIdIndexRouteImport } from './app/routes/puppies.$breedId.index'
import { Route as PuppiesBreedIdPuppyIdRouteImport } from './app/routes/puppies.$breedId.$puppyId'

const PuppiesRoute = PuppiesRouteImport.update({
  id: '/puppies',
  path: '/puppies',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppiesBreedIdRoute = PuppiesBreedIdRouteImport.update({
  id: '/$breedId',
  path: '/$breedId',
  getParentRoute: () => PuppiesRoute,
} as any)
const PuppiesBreedIdIndexRoute = PuppiesBreedIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PuppiesBreedIdRoute,
} as any)
const PuppiesBreedIdPuppyIdRoute = PuppiesBreedIdPuppyIdRouteImport.update({
  id: '/$puppyId',
  path: '/$puppyId',
  getParentRoute: () => PuppiesBreedIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/library': typeof LibraryRoute
  '/puppies': typeof PuppiesRouteWithChildren
  '/puppies/$breedId': typeof PuppiesBreedIdRouteWithChildren
  '/puppies/$breedId/$puppyId': typeof PuppiesBreedIdPuppyIdRoute
  '/puppies/$breedId/': typeof PuppiesBreedIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/library': typeof LibraryRoute
  '/puppies': typeof PuppiesRouteWithChildren
  '/puppies/$breedId/$puppyId': typeof PuppiesBreedIdPuppyIdRoute
  '/puppies/$breedId': typeof PuppiesBreedIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/library': typeof LibraryRoute
  '/puppies': typeof PuppiesRouteWithChildren
  '/puppies/$breedId': typeof PuppiesBreedIdRouteWithChildren
  '/puppies/$breedId/$puppyId': typeof PuppiesBreedIdPuppyIdRoute
  '/puppies/$breedId/': typeof PuppiesBreedIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contacts'
    | '/library'
    | '/puppies'
    | '/puppies/$breedId'
    | '/puppies/$breedId/$puppyId'
    | '/puppies/$breedId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contacts'
    | '/library'
    | '/puppies'
    | '/puppies/$breedId/$puppyId'
    | '/puppies/$breedId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contacts'
    | '/library'
    | '/puppies'
    | '/puppies/$breedId'
    | '/puppies/$breedId/$puppyId'
    | '/puppies/$breedId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  LibraryRoute: typeof LibraryRoute
  PuppiesRoute: typeof PuppiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/puppies': {
      id: '/puppies'
      path: '/puppies'
      fullPath: '/puppies'
      preLoaderRoute: typeof PuppiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppies/$breedId': {
      id: '/puppies/$breedId'
      path: '/$breedId'
      fullPath: '/puppies/$breedId'
      preLoaderRoute: typeof PuppiesBreedIdRouteImport
      parentRoute: typeof PuppiesRoute
    }
    '/puppies/$breedId/': {
      id: '/puppies/$breedId/'
      path: '/'
      fullPath: '/puppies/$breedId/'
      preLoaderRoute: typeof PuppiesBreedIdIndexRouteImport
      parentRoute: typeof PuppiesBreedIdRoute
    }
    '/puppies/$breedId/$puppyId': {
      id: '/puppies/$breedId/$puppyId'
      path: '/$puppyId'
      fullPath: '/puppies/$breedId/$puppyId'
      preLoaderRoute: typeof PuppiesBreedIdPuppyIdRouteImport
      parentRoute: typeof PuppiesBreedIdRoute
    }
  }
}

interface PuppiesBreedIdRouteChildren {
  PuppiesBreedIdPuppyIdRoute: typeof PuppiesBreedIdPuppyIdRoute
  PuppiesBreedIdIndexRoute: typeof PuppiesBreedIdIndexRoute
}

const PuppiesBreedIdRouteChildren: PuppiesBreedIdRouteChildren = {
  PuppiesBreedIdPuppyIdRoute: PuppiesBreedIdPuppyIdRoute,
  PuppiesBreedIdIndexRoute: PuppiesBreedIdIndexRoute,
}

const PuppiesBreedIdRouteWithChildren = PuppiesBreedIdRoute._addFileChildren(
  PuppiesBreedIdRouteChildren,
)

interface PuppiesRouteChildren {
  PuppiesBreedIdRoute: typeof PuppiesBreedIdRouteWithChildren
}

const PuppiesRouteChildren: PuppiesRouteChildren = {
  PuppiesBreedIdRoute: PuppiesBreedIdRouteWithChildren,
}

const PuppiesRouteWithChildren =
  PuppiesRoute._addFileChildren(PuppiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  LibraryRoute: LibraryRoute,
  PuppiesRoute: PuppiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
