/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as KnowledgeBaseRouteImport } from './app/routes/knowledge-base'
import { Route as ContactsRouteImport } from './app/routes/contacts'
import { Route as AboutRouteImport } from './app/routes/about'
import { Route as PuppiesRouteRouteImport } from './app/routes/puppies/route'
import { Route as DogsRouteRouteImport } from './app/routes/dogs/route'
import { Route as CabinetRouteRouteImport } from './app/routes/cabinet/route'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as CabinetIndexRouteImport } from './app/routes/cabinet/index'
import { Route as PuppiesBreedIdRouteImport } from './app/routes/puppies/$breedId'
import { Route as DogsBreedIdRouteImport } from './app/routes/dogs/$breedId'
import { Route as CoursesSlugRouteImport } from './app/routes/courses/$slug'
import { Route as CabinetSettingsRouteImport } from './app/routes/cabinet/settings'
import { Route as CabinetRequestsRouteImport } from './app/routes/cabinet/requests'
import { Route as CabinetNurseryRouteImport } from './app/routes/cabinet/nursery'
import { Route as CabinetMyRequestsRouteImport } from './app/routes/cabinet/my-requests'
import { Route as CabinetMyCoursesRouteImport } from './app/routes/cabinet/my-courses'
import { Route as CabinetCoursesRouteImport } from './app/routes/cabinet/courses'
import { Route as CabinetArticlesRouteImport } from './app/routes/cabinet/articles'
import { Route as ArticlesSlugRouteImport } from './app/routes/articles/$slug'
import { Route as PuppiesBreedIdIndexRouteImport } from './app/routes/puppies/$breedId/index'
import { Route as DogsBreedIdIndexRouteImport } from './app/routes/dogs/$breedId/index'
import { Route as PuppiesBreedIdPuppyIdRouteImport } from './app/routes/puppies/$breedId/$puppyId'
import { Route as DogsBreedIdDogIdRouteImport } from './app/routes/dogs/$breedId/$dogId'
import { Route as CabinetRequestsNewRouteImport } from './app/routes/cabinet/requests.new'
import { Route as CabinetRequestsRequestIdRouteImport } from './app/routes/cabinet/requests.$requestId'
import { Route as CabinetNurseryNewRouteImport } from './app/routes/cabinet/nursery.new'
import { Route as CabinetNurseryDogIdRouteImport } from './app/routes/cabinet/nursery.$dogId'
import { Route as CabinetCoursesNewRouteImport } from './app/routes/cabinet/courses.new'
import { Route as CabinetCoursesCourseSlugRouteImport } from './app/routes/cabinet/courses.$courseSlug'
import { Route as CabinetArticlesNewRouteImport } from './app/routes/cabinet/articles.new'
import { Route as CabinetArticlesArticleSlugRouteImport } from './app/routes/cabinet/articles.$articleSlug'

const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppiesRouteRoute = PuppiesRouteRouteImport.update({
  id: '/puppies',
  path: '/puppies',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsRouteRoute = DogsRouteRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRouteRoute = CabinetRouteRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetIndexRoute = CabinetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const PuppiesBreedIdRoute = PuppiesBreedIdRouteImport.update({
  id: '/$breedId',
  path: '/$breedId',
  getParentRoute: () => PuppiesRouteRoute,
} as any)
const DogsBreedIdRoute = DogsBreedIdRouteImport.update({
  id: '/$breedId',
  path: '/$breedId',
  getParentRoute: () => DogsRouteRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetSettingsRoute = CabinetSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const CabinetRequestsRoute = CabinetRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const CabinetNurseryRoute = CabinetNurseryRouteImport.update({
  id: '/nursery',
  path: '/nursery',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const CabinetMyRequestsRoute = CabinetMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const CabinetMyCoursesRoute = CabinetMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const CabinetCoursesRoute = CabinetCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const CabinetArticlesRoute = CabinetArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => CabinetRouteRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppiesBreedIdIndexRoute = PuppiesBreedIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PuppiesBreedIdRoute,
} as any)
const DogsBreedIdIndexRoute = DogsBreedIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DogsBreedIdRoute,
} as any)
const PuppiesBreedIdPuppyIdRoute = PuppiesBreedIdPuppyIdRouteImport.update({
  id: '/$puppyId',
  path: '/$puppyId',
  getParentRoute: () => PuppiesBreedIdRoute,
} as any)
const DogsBreedIdDogIdRoute = DogsBreedIdDogIdRouteImport.update({
  id: '/$dogId',
  path: '/$dogId',
  getParentRoute: () => DogsBreedIdRoute,
} as any)
const CabinetRequestsNewRoute = CabinetRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CabinetRequestsRoute,
} as any)
const CabinetRequestsRequestIdRoute =
  CabinetRequestsRequestIdRouteImport.update({
    id: '/$requestId',
    path: '/$requestId',
    getParentRoute: () => CabinetRequestsRoute,
  } as any)
const CabinetNurseryNewRoute = CabinetNurseryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CabinetNurseryRoute,
} as any)
const CabinetNurseryDogIdRoute = CabinetNurseryDogIdRouteImport.update({
  id: '/$dogId',
  path: '/$dogId',
  getParentRoute: () => CabinetNurseryRoute,
} as any)
const CabinetCoursesNewRoute = CabinetCoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CabinetCoursesRoute,
} as any)
const CabinetCoursesCourseSlugRoute =
  CabinetCoursesCourseSlugRouteImport.update({
    id: '/$courseSlug',
    path: '/$courseSlug',
    getParentRoute: () => CabinetCoursesRoute,
  } as any)
const CabinetArticlesNewRoute = CabinetArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CabinetArticlesRoute,
} as any)
const CabinetArticlesArticleSlugRoute =
  CabinetArticlesArticleSlugRouteImport.update({
    id: '/$articleSlug',
    path: '/$articleSlug',
    getParentRoute: () => CabinetArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRouteRouteWithChildren
  '/dogs': typeof DogsRouteRouteWithChildren
  '/puppies': typeof PuppiesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/cabinet/articles': typeof CabinetArticlesRouteWithChildren
  '/cabinet/courses': typeof CabinetCoursesRouteWithChildren
  '/cabinet/my-courses': typeof CabinetMyCoursesRoute
  '/cabinet/my-requests': typeof CabinetMyRequestsRoute
  '/cabinet/nursery': typeof CabinetNurseryRouteWithChildren
  '/cabinet/requests': typeof CabinetRequestsRouteWithChildren
  '/cabinet/settings': typeof CabinetSettingsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dogs/$breedId': typeof DogsBreedIdRouteWithChildren
  '/puppies/$breedId': typeof PuppiesBreedIdRouteWithChildren
  '/cabinet/': typeof CabinetIndexRoute
  '/cabinet/articles/$articleSlug': typeof CabinetArticlesArticleSlugRoute
  '/cabinet/articles/new': typeof CabinetArticlesNewRoute
  '/cabinet/courses/$courseSlug': typeof CabinetCoursesCourseSlugRoute
  '/cabinet/courses/new': typeof CabinetCoursesNewRoute
  '/cabinet/nursery/$dogId': typeof CabinetNurseryDogIdRoute
  '/cabinet/nursery/new': typeof CabinetNurseryNewRoute
  '/cabinet/requests/$requestId': typeof CabinetRequestsRequestIdRoute
  '/cabinet/requests/new': typeof CabinetRequestsNewRoute
  '/dogs/$breedId/$dogId': typeof DogsBreedIdDogIdRoute
  '/puppies/$breedId/$puppyId': typeof PuppiesBreedIdPuppyIdRoute
  '/dogs/$breedId/': typeof DogsBreedIdIndexRoute
  '/puppies/$breedId/': typeof PuppiesBreedIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dogs': typeof DogsRouteRouteWithChildren
  '/puppies': typeof PuppiesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/cabinet/articles': typeof CabinetArticlesRouteWithChildren
  '/cabinet/courses': typeof CabinetCoursesRouteWithChildren
  '/cabinet/my-courses': typeof CabinetMyCoursesRoute
  '/cabinet/my-requests': typeof CabinetMyRequestsRoute
  '/cabinet/nursery': typeof CabinetNurseryRouteWithChildren
  '/cabinet/requests': typeof CabinetRequestsRouteWithChildren
  '/cabinet/settings': typeof CabinetSettingsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/cabinet': typeof CabinetIndexRoute
  '/cabinet/articles/$articleSlug': typeof CabinetArticlesArticleSlugRoute
  '/cabinet/articles/new': typeof CabinetArticlesNewRoute
  '/cabinet/courses/$courseSlug': typeof CabinetCoursesCourseSlugRoute
  '/cabinet/courses/new': typeof CabinetCoursesNewRoute
  '/cabinet/nursery/$dogId': typeof CabinetNurseryDogIdRoute
  '/cabinet/nursery/new': typeof CabinetNurseryNewRoute
  '/cabinet/requests/$requestId': typeof CabinetRequestsRequestIdRoute
  '/cabinet/requests/new': typeof CabinetRequestsNewRoute
  '/dogs/$breedId/$dogId': typeof DogsBreedIdDogIdRoute
  '/puppies/$breedId/$puppyId': typeof PuppiesBreedIdPuppyIdRoute
  '/dogs/$breedId': typeof DogsBreedIdIndexRoute
  '/puppies/$breedId': typeof PuppiesBreedIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRouteRouteWithChildren
  '/dogs': typeof DogsRouteRouteWithChildren
  '/puppies': typeof PuppiesRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contacts': typeof ContactsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/cabinet/articles': typeof CabinetArticlesRouteWithChildren
  '/cabinet/courses': typeof CabinetCoursesRouteWithChildren
  '/cabinet/my-courses': typeof CabinetMyCoursesRoute
  '/cabinet/my-requests': typeof CabinetMyRequestsRoute
  '/cabinet/nursery': typeof CabinetNurseryRouteWithChildren
  '/cabinet/requests': typeof CabinetRequestsRouteWithChildren
  '/cabinet/settings': typeof CabinetSettingsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dogs/$breedId': typeof DogsBreedIdRouteWithChildren
  '/puppies/$breedId': typeof PuppiesBreedIdRouteWithChildren
  '/cabinet/': typeof CabinetIndexRoute
  '/cabinet/articles/$articleSlug': typeof CabinetArticlesArticleSlugRoute
  '/cabinet/articles/new': typeof CabinetArticlesNewRoute
  '/cabinet/courses/$courseSlug': typeof CabinetCoursesCourseSlugRoute
  '/cabinet/courses/new': typeof CabinetCoursesNewRoute
  '/cabinet/nursery/$dogId': typeof CabinetNurseryDogIdRoute
  '/cabinet/nursery/new': typeof CabinetNurseryNewRoute
  '/cabinet/requests/$requestId': typeof CabinetRequestsRequestIdRoute
  '/cabinet/requests/new': typeof CabinetRequestsNewRoute
  '/dogs/$breedId/$dogId': typeof DogsBreedIdDogIdRoute
  '/puppies/$breedId/$puppyId': typeof PuppiesBreedIdPuppyIdRoute
  '/dogs/$breedId/': typeof DogsBreedIdIndexRoute
  '/puppies/$breedId/': typeof PuppiesBreedIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabinet'
    | '/dogs'
    | '/puppies'
    | '/about'
    | '/contacts'
    | '/knowledge-base'
    | '/articles/$slug'
    | '/cabinet/articles'
    | '/cabinet/courses'
    | '/cabinet/my-courses'
    | '/cabinet/my-requests'
    | '/cabinet/nursery'
    | '/cabinet/requests'
    | '/cabinet/settings'
    | '/courses/$slug'
    | '/dogs/$breedId'
    | '/puppies/$breedId'
    | '/cabinet/'
    | '/cabinet/articles/$articleSlug'
    | '/cabinet/articles/new'
    | '/cabinet/courses/$courseSlug'
    | '/cabinet/courses/new'
    | '/cabinet/nursery/$dogId'
    | '/cabinet/nursery/new'
    | '/cabinet/requests/$requestId'
    | '/cabinet/requests/new'
    | '/dogs/$breedId/$dogId'
    | '/puppies/$breedId/$puppyId'
    | '/dogs/$breedId/'
    | '/puppies/$breedId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dogs'
    | '/puppies'
    | '/about'
    | '/contacts'
    | '/knowledge-base'
    | '/articles/$slug'
    | '/cabinet/articles'
    | '/cabinet/courses'
    | '/cabinet/my-courses'
    | '/cabinet/my-requests'
    | '/cabinet/nursery'
    | '/cabinet/requests'
    | '/cabinet/settings'
    | '/courses/$slug'
    | '/cabinet'
    | '/cabinet/articles/$articleSlug'
    | '/cabinet/articles/new'
    | '/cabinet/courses/$courseSlug'
    | '/cabinet/courses/new'
    | '/cabinet/nursery/$dogId'
    | '/cabinet/nursery/new'
    | '/cabinet/requests/$requestId'
    | '/cabinet/requests/new'
    | '/dogs/$breedId/$dogId'
    | '/puppies/$breedId/$puppyId'
    | '/dogs/$breedId'
    | '/puppies/$breedId'
  id:
    | '__root__'
    | '/'
    | '/cabinet'
    | '/dogs'
    | '/puppies'
    | '/about'
    | '/contacts'
    | '/knowledge-base'
    | '/articles/$slug'
    | '/cabinet/articles'
    | '/cabinet/courses'
    | '/cabinet/my-courses'
    | '/cabinet/my-requests'
    | '/cabinet/nursery'
    | '/cabinet/requests'
    | '/cabinet/settings'
    | '/courses/$slug'
    | '/dogs/$breedId'
    | '/puppies/$breedId'
    | '/cabinet/'
    | '/cabinet/articles/$articleSlug'
    | '/cabinet/articles/new'
    | '/cabinet/courses/$courseSlug'
    | '/cabinet/courses/new'
    | '/cabinet/nursery/$dogId'
    | '/cabinet/nursery/new'
    | '/cabinet/requests/$requestId'
    | '/cabinet/requests/new'
    | '/dogs/$breedId/$dogId'
    | '/puppies/$breedId/$puppyId'
    | '/dogs/$breedId/'
    | '/puppies/$breedId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRouteRoute: typeof CabinetRouteRouteWithChildren
  DogsRouteRoute: typeof DogsRouteRouteWithChildren
  PuppiesRouteRoute: typeof PuppiesRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactsRoute: typeof ContactsRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppies': {
      id: '/puppies'
      path: '/puppies'
      fullPath: '/puppies'
      preLoaderRoute: typeof PuppiesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs': {
      id: '/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof DogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/': {
      id: '/cabinet/'
      path: '/'
      fullPath: '/cabinet/'
      preLoaderRoute: typeof CabinetIndexRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/puppies/$breedId': {
      id: '/puppies/$breedId'
      path: '/$breedId'
      fullPath: '/puppies/$breedId'
      preLoaderRoute: typeof PuppiesBreedIdRouteImport
      parentRoute: typeof PuppiesRouteRoute
    }
    '/dogs/$breedId': {
      id: '/dogs/$breedId'
      path: '/$breedId'
      fullPath: '/dogs/$breedId'
      preLoaderRoute: typeof DogsBreedIdRouteImport
      parentRoute: typeof DogsRouteRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/settings': {
      id: '/cabinet/settings'
      path: '/settings'
      fullPath: '/cabinet/settings'
      preLoaderRoute: typeof CabinetSettingsRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/requests': {
      id: '/cabinet/requests'
      path: '/requests'
      fullPath: '/cabinet/requests'
      preLoaderRoute: typeof CabinetRequestsRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/nursery': {
      id: '/cabinet/nursery'
      path: '/nursery'
      fullPath: '/cabinet/nursery'
      preLoaderRoute: typeof CabinetNurseryRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/my-requests': {
      id: '/cabinet/my-requests'
      path: '/my-requests'
      fullPath: '/cabinet/my-requests'
      preLoaderRoute: typeof CabinetMyRequestsRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/my-courses': {
      id: '/cabinet/my-courses'
      path: '/my-courses'
      fullPath: '/cabinet/my-courses'
      preLoaderRoute: typeof CabinetMyCoursesRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/courses': {
      id: '/cabinet/courses'
      path: '/courses'
      fullPath: '/cabinet/courses'
      preLoaderRoute: typeof CabinetCoursesRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/cabinet/articles': {
      id: '/cabinet/articles'
      path: '/articles'
      fullPath: '/cabinet/articles'
      preLoaderRoute: typeof CabinetArticlesRouteImport
      parentRoute: typeof CabinetRouteRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppies/$breedId/': {
      id: '/puppies/$breedId/'
      path: '/'
      fullPath: '/puppies/$breedId/'
      preLoaderRoute: typeof PuppiesBreedIdIndexRouteImport
      parentRoute: typeof PuppiesBreedIdRoute
    }
    '/dogs/$breedId/': {
      id: '/dogs/$breedId/'
      path: '/'
      fullPath: '/dogs/$breedId/'
      preLoaderRoute: typeof DogsBreedIdIndexRouteImport
      parentRoute: typeof DogsBreedIdRoute
    }
    '/puppies/$breedId/$puppyId': {
      id: '/puppies/$breedId/$puppyId'
      path: '/$puppyId'
      fullPath: '/puppies/$breedId/$puppyId'
      preLoaderRoute: typeof PuppiesBreedIdPuppyIdRouteImport
      parentRoute: typeof PuppiesBreedIdRoute
    }
    '/dogs/$breedId/$dogId': {
      id: '/dogs/$breedId/$dogId'
      path: '/$dogId'
      fullPath: '/dogs/$breedId/$dogId'
      preLoaderRoute: typeof DogsBreedIdDogIdRouteImport
      parentRoute: typeof DogsBreedIdRoute
    }
    '/cabinet/requests/new': {
      id: '/cabinet/requests/new'
      path: '/new'
      fullPath: '/cabinet/requests/new'
      preLoaderRoute: typeof CabinetRequestsNewRouteImport
      parentRoute: typeof CabinetRequestsRoute
    }
    '/cabinet/requests/$requestId': {
      id: '/cabinet/requests/$requestId'
      path: '/$requestId'
      fullPath: '/cabinet/requests/$requestId'
      preLoaderRoute: typeof CabinetRequestsRequestIdRouteImport
      parentRoute: typeof CabinetRequestsRoute
    }
    '/cabinet/nursery/new': {
      id: '/cabinet/nursery/new'
      path: '/new'
      fullPath: '/cabinet/nursery/new'
      preLoaderRoute: typeof CabinetNurseryNewRouteImport
      parentRoute: typeof CabinetNurseryRoute
    }
    '/cabinet/nursery/$dogId': {
      id: '/cabinet/nursery/$dogId'
      path: '/$dogId'
      fullPath: '/cabinet/nursery/$dogId'
      preLoaderRoute: typeof CabinetNurseryDogIdRouteImport
      parentRoute: typeof CabinetNurseryRoute
    }
    '/cabinet/courses/new': {
      id: '/cabinet/courses/new'
      path: '/new'
      fullPath: '/cabinet/courses/new'
      preLoaderRoute: typeof CabinetCoursesNewRouteImport
      parentRoute: typeof CabinetCoursesRoute
    }
    '/cabinet/courses/$courseSlug': {
      id: '/cabinet/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/cabinet/courses/$courseSlug'
      preLoaderRoute: typeof CabinetCoursesCourseSlugRouteImport
      parentRoute: typeof CabinetCoursesRoute
    }
    '/cabinet/articles/new': {
      id: '/cabinet/articles/new'
      path: '/new'
      fullPath: '/cabinet/articles/new'
      preLoaderRoute: typeof CabinetArticlesNewRouteImport
      parentRoute: typeof CabinetArticlesRoute
    }
    '/cabinet/articles/$articleSlug': {
      id: '/cabinet/articles/$articleSlug'
      path: '/$articleSlug'
      fullPath: '/cabinet/articles/$articleSlug'
      preLoaderRoute: typeof CabinetArticlesArticleSlugRouteImport
      parentRoute: typeof CabinetArticlesRoute
    }
  }
}

interface CabinetArticlesRouteChildren {
  CabinetArticlesArticleSlugRoute: typeof CabinetArticlesArticleSlugRoute
  CabinetArticlesNewRoute: typeof CabinetArticlesNewRoute
}

const CabinetArticlesRouteChildren: CabinetArticlesRouteChildren = {
  CabinetArticlesArticleSlugRoute: CabinetArticlesArticleSlugRoute,
  CabinetArticlesNewRoute: CabinetArticlesNewRoute,
}

const CabinetArticlesRouteWithChildren = CabinetArticlesRoute._addFileChildren(
  CabinetArticlesRouteChildren,
)

interface CabinetCoursesRouteChildren {
  CabinetCoursesCourseSlugRoute: typeof CabinetCoursesCourseSlugRoute
  CabinetCoursesNewRoute: typeof CabinetCoursesNewRoute
}

const CabinetCoursesRouteChildren: CabinetCoursesRouteChildren = {
  CabinetCoursesCourseSlugRoute: CabinetCoursesCourseSlugRoute,
  CabinetCoursesNewRoute: CabinetCoursesNewRoute,
}

const CabinetCoursesRouteWithChildren = CabinetCoursesRoute._addFileChildren(
  CabinetCoursesRouteChildren,
)

interface CabinetNurseryRouteChildren {
  CabinetNurseryDogIdRoute: typeof CabinetNurseryDogIdRoute
  CabinetNurseryNewRoute: typeof CabinetNurseryNewRoute
}

const CabinetNurseryRouteChildren: CabinetNurseryRouteChildren = {
  CabinetNurseryDogIdRoute: CabinetNurseryDogIdRoute,
  CabinetNurseryNewRoute: CabinetNurseryNewRoute,
}

const CabinetNurseryRouteWithChildren = CabinetNurseryRoute._addFileChildren(
  CabinetNurseryRouteChildren,
)

interface CabinetRequestsRouteChildren {
  CabinetRequestsRequestIdRoute: typeof CabinetRequestsRequestIdRoute
  CabinetRequestsNewRoute: typeof CabinetRequestsNewRoute
}

const CabinetRequestsRouteChildren: CabinetRequestsRouteChildren = {
  CabinetRequestsRequestIdRoute: CabinetRequestsRequestIdRoute,
  CabinetRequestsNewRoute: CabinetRequestsNewRoute,
}

const CabinetRequestsRouteWithChildren = CabinetRequestsRoute._addFileChildren(
  CabinetRequestsRouteChildren,
)

interface CabinetRouteRouteChildren {
  CabinetArticlesRoute: typeof CabinetArticlesRouteWithChildren
  CabinetCoursesRoute: typeof CabinetCoursesRouteWithChildren
  CabinetMyCoursesRoute: typeof CabinetMyCoursesRoute
  CabinetMyRequestsRoute: typeof CabinetMyRequestsRoute
  CabinetNurseryRoute: typeof CabinetNurseryRouteWithChildren
  CabinetRequestsRoute: typeof CabinetRequestsRouteWithChildren
  CabinetSettingsRoute: typeof CabinetSettingsRoute
  CabinetIndexRoute: typeof CabinetIndexRoute
}

const CabinetRouteRouteChildren: CabinetRouteRouteChildren = {
  CabinetArticlesRoute: CabinetArticlesRouteWithChildren,
  CabinetCoursesRoute: CabinetCoursesRouteWithChildren,
  CabinetMyCoursesRoute: CabinetMyCoursesRoute,
  CabinetMyRequestsRoute: CabinetMyRequestsRoute,
  CabinetNurseryRoute: CabinetNurseryRouteWithChildren,
  CabinetRequestsRoute: CabinetRequestsRouteWithChildren,
  CabinetSettingsRoute: CabinetSettingsRoute,
  CabinetIndexRoute: CabinetIndexRoute,
}

const CabinetRouteRouteWithChildren = CabinetRouteRoute._addFileChildren(
  CabinetRouteRouteChildren,
)

interface DogsBreedIdRouteChildren {
  DogsBreedIdDogIdRoute: typeof DogsBreedIdDogIdRoute
  DogsBreedIdIndexRoute: typeof DogsBreedIdIndexRoute
}

const DogsBreedIdRouteChildren: DogsBreedIdRouteChildren = {
  DogsBreedIdDogIdRoute: DogsBreedIdDogIdRoute,
  DogsBreedIdIndexRoute: DogsBreedIdIndexRoute,
}

const DogsBreedIdRouteWithChildren = DogsBreedIdRoute._addFileChildren(
  DogsBreedIdRouteChildren,
)

interface DogsRouteRouteChildren {
  DogsBreedIdRoute: typeof DogsBreedIdRouteWithChildren
}

const DogsRouteRouteChildren: DogsRouteRouteChildren = {
  DogsBreedIdRoute: DogsBreedIdRouteWithChildren,
}

const DogsRouteRouteWithChildren = DogsRouteRoute._addFileChildren(
  DogsRouteRouteChildren,
)

interface PuppiesBreedIdRouteChildren {
  PuppiesBreedIdPuppyIdRoute: typeof PuppiesBreedIdPuppyIdRoute
  PuppiesBreedIdIndexRoute: typeof PuppiesBreedIdIndexRoute
}

const PuppiesBreedIdRouteChildren: PuppiesBreedIdRouteChildren = {
  PuppiesBreedIdPuppyIdRoute: PuppiesBreedIdPuppyIdRoute,
  PuppiesBreedIdIndexRoute: PuppiesBreedIdIndexRoute,
}

const PuppiesBreedIdRouteWithChildren = PuppiesBreedIdRoute._addFileChildren(
  PuppiesBreedIdRouteChildren,
)

interface PuppiesRouteRouteChildren {
  PuppiesBreedIdRoute: typeof PuppiesBreedIdRouteWithChildren
}

const PuppiesRouteRouteChildren: PuppiesRouteRouteChildren = {
  PuppiesBreedIdRoute: PuppiesBreedIdRouteWithChildren,
}

const PuppiesRouteRouteWithChildren = PuppiesRouteRoute._addFileChildren(
  PuppiesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRouteRoute: CabinetRouteRouteWithChildren,
  DogsRouteRoute: DogsRouteRouteWithChildren,
  PuppiesRouteRoute: PuppiesRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactsRoute: ContactsRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
